# 내 프로젝트에서 사용
mapping_color_map:
    0 : [255, 0, 0]         # car
    1 : [0, 255, 0]         # other-vehicle
    2 : [0, 0, 255]         # road
    3 : [0, 255, 255]       # sidewalk
    4 : [255, 255, 255]     # unlabeled

# kitti
kitti:
    color_map:
        0   : [255, 255, 255]  # unlabeled: 흰색
        1   : [0, 0, 255]      # outlier: 파란색
        10  : [245, 150, 100]  # car: 살구색
        11  : [245, 230, 100]  # bicycle: 연노랑
        13  : [250, 80, 100]   # bus: 연분홍
        15  : [150, 60, 30]    # motorcycle: 갈색
        16  : [255, 0, 0]      # on-rails: 빨간색
        18  : [180, 30, 80]    # truck: 자홍색
        20  : [255, 0, 0]      # other-vehicle: 빨간색
        30  : [30, 30, 255]    # person: 진파랑
        31  : [200, 40, 255]   # bicyclist: 마젠타
        32  : [90, 30, 150]    # motorcyclist: 보라색
        40  : [255, 0, 255]    # road: 마젠타
        44  : [255, 150, 255]  # parking: 연보라
        48  : [75, 0, 75]      # sidewalk: 다크퍼플
        49  : [75, 0, 175]     # other-ground: 진보라   
        50  : [0, 200, 255]    # building: 청록색
        51  : [50, 120, 255]   # fence: 하늘파랑
        52  : [0, 150, 255]    # other-structure: 밝은 청록
        60  : [170, 255, 150]  # lane-marking: 민트색
        70  : [0, 175, 0]      # vegetation: 초록색
        71  : [0, 60, 135]     # trunk: 다크블루
        72  : [80, 240, 150]   # terrain: 연초록
        80  : [150, 240, 255]  # pole: 연하늘
        81  : [0, 0, 255]      # traffic-sign: 파란색
        99  : [255, 255, 50]   # other-object: 연노랑
        252 : [245, 150, 100]  # moving-car: 살구색
        256 : [255, 0, 0]      # moving-on-rails: 빨간색
        253 : [200, 40, 255]   # moving-bicyclist: 마젠타
        254 : [30, 30, 255]    # moving-person: 진파랑
        255 : [90, 30, 150]    # moving-motorcyclist: 보라색
        257 : [250, 80, 100]   # moving-bus: 연분홍
        258 : [180, 30, 80]    # moving-truck: 자홍색
        259 : [255, 0, 0]      # moving-other-vehicle: 빨간색


    label_map:
        0   : 4  # unlabeled                   -> 4: unlabeled
        1   : 4  # outlier                     -> 4: unlabeled
        10  : 0  # car                         -> 0: car
        11  : 1  # bicycle                     -> 1: other-vehicle
        13  : 0  # bus                         -> 0: car
        15  : 1  # motorcycle                  -> 1: other-vehicle
        16  : 1  # on-rails                    -> 1: other-vehicle
        18  : 0  # truck                       -> 0: car
        20  : 1  # other-vehicle               -> 1: other-vehicle
        30  : 1  # person                      -> 1: other-vehicle
        31  : 1  # bicyclist                   -> 1: other-vehicle
        32  : 1  # motorcyclist                -> 1: other-vehicle
        40  : 2  # road                        -> 2: road
        44  : 2  # parking                     -> 2: road
        48  : 3  # sidewalk                    -> 3: sidewalk
        49  : 4  # other-ground                -> 4: unlabeled
        50  : 4  # building                    -> 4: unlabeled
        51  : 4  # fence                       -> 4: unlabeled
        52  : 4  # other-structure             -> 4: unlabeled
        60  : 2  # lane-marking                -> 2: road
        70  : 4  # vegetation                  -> 4: unlabeled
        71  : 4  # trunk                       -> 4: unlabeled
        72  : 4  # terrain                     -> 4: unlabeled
        80  : 4  # pole                        -> 4: unlabeled
        81  : 4  # traffic-sign                -> 4: unlabeled
        99  : 4  # other-object                -> 4: unlabeled
        252 : 0  # moving-car                  -> 0: car
        253 : 1  # moving-bicyclist            -> 1: other-vehicle
        254 : 1  # moving-person               -> 1: other-vehicle
        255 : 1  # moving-motorcyclist         -> 1: other-vehicle
        256 : 1  # moving-on-rails             -> 1: other-vehicle
        257 : 1  # moving-bus                  -> 1: other-vehicle
        258 : 0  # moving-truck                -> 0: car
        259 : 1  # moving-other-vehicle        -> 1: other-vehicle