# LiDAR 정보
lidar:
    "manufacturer": "lidar"
    "H": 64
    "W": 1024
    "fov_up": 23.0
    "fov_down": -23.0


# 라벨 정보 (사용 X)
# KITTI랑 동일
labels:
    0 : "car"
    1 : "other-vehicle"
    2 : "road"
    3 : "sidewalk"
    4 : "unlabled"

# color_map:
#     0 : [255, 0, 0]         # car
#     1 : [0, 255, 0]         # other-vehicle
#     2 : [0, 0, 255]         # road
#     3 : [0, 255, 255]       # sidewalk
#     4 : [255, 255, 255]     # unlabeled

color_map:
    0   : [255, 255, 255]  # unlabeled
    10  : [255,   0,   0]  # car
    11  : [  0, 255,   0]  # other-vehicle (정지)
    12  : [  0, 255, 255]  # ground
    13  : [255, 255, 255]  # 컨테이너? 쓰레기 담는 엄청 큰 통?
    30  : [  0, 255,   0]  # people
    31  : [  0, 255,   0]  # other-vehicle (이동)
    40  : [  0,   0, 255]  # road
    48  : [  0, 255, 255]  # sidewalk
    49  : [  0, 255, 255]  # sidewalk
    50  : [255, 255, 255]  # building
    51  : [255, 255, 255]  # 울타리
    52  : [255, 255, 255]  # 막사? 정자?
    70  : [255, 255, 255]  # 나뭇잎
    71  : [255, 255, 255]  # 나무 (줄기)
    72  : [  0, 255, 255]  # sidewalk
    80  : [255, 255, 255]  # 신호등 (줄기)
    81  : [255, 255, 255]  # 신호등 (신호표시기)
    82  : [255, 255, 255]  # 자판기? 비석?
    99  : [255, 255, 255]  # 도로 위에 못가게 막아두는 작은 통