# LiDAR 정보
lidar:
    "manufacturer": "velodyne"
    "H": 64
    "W": 1024
    "fov_up": 3.0
    "fov_down": -25.0


# 라벨 정보 (사용 X)
labels:
    0 : "unlabeled"
    1 : "outlier"
    10: "car"
    11: "bicycle"
    13: "bus"
    15: "motorcycle"
    16: "on-rails"
    18: "truck"
    20: "other-vehicle"
    30: "person"
    31: "bicyclist"
    32: "motorcyclist"
    40: "road"
    44: "parking"
    48: "sidewalk"
    49: "other-ground"
    50: "building"
    51: "fence"
    52: "other-structure"
    60: "lane-marking"
    70: "vegetation"
    71: "trunk"
    72: "terrain"
    80: "pole"
    81: "traffic-sign"
    99: "other-object"
    252: "moving-car"
    253: "moving-bicyclist"
    254: "moving-person"
    255: "moving-motorcyclist"
    256: "moving-on-rails"
    257: "moving-bus"
    258: "moving-truck"
    259: "moving-other-vehicle"


# 라벨별 BGR 색상 매핑 설정
color_map:
    0   : [255, 255, 255]  # unlabeled: 흰색
    1   : [0, 0, 255]      # outlier: 파란색
    10  : [245, 150, 100]  # car: 살구색
    11  : [245, 230, 100]  # bicycle: 연노랑
    13  : [250, 80, 100]   # bus: 연분홍
    15  : [150, 60, 30]    # motorcycle: 갈색
    16  : [255, 0, 0]      # on-rails: 빨간색
    18  : [180, 30, 80]    # truck: 자홍색
    20  : [255, 0, 0]      # other-vehicle: 빨간색
    30  : [30, 30, 255]    # person: 진파랑
    31  : [200, 40, 255]   # bicyclist: 마젠타
    32  : [90, 30, 150]    # motorcyclist: 보라색
    40  : [255, 0, 255]    # road: 마젠타
    44  : [255, 150, 255]  # parking: 연보라
    48  : [75, 0, 75]      # sidewalk: 다크퍼플
    49  : [75, 0, 175]     # other-ground: 진보라
    50  : [0, 200, 255]    # building: 청록색
    51  : [50, 120, 255]   # fence: 하늘파랑
    52  : [0, 150, 255]    # other-structure: 밝은 청록
    60  : [170, 255, 150]  # lane-marking: 민트색
    70  : [0, 175, 0]      # vegetation: 초록색
    71  : [0, 60, 135]     # trunk: 다크블루
    72  : [80, 240, 150]   # terrain: 연초록
    80  : [150, 240, 255]  # pole: 연하늘
    81  : [0, 0, 255]      # traffic-sign: 파란색
    99  : [255, 255, 50]   # other-object: 연노랑
    252 : [245, 150, 100]  # moving-car: 살구색
    256 : [255, 0, 0]      # moving-on-rails: 빨간색
    253 : [200, 40, 255]   # moving-bicyclist: 마젠타
    254 : [30, 30, 255]    # moving-person: 진파랑
    255 : [90, 30, 150]    # moving-motorcyclist: 보라색
    257 : [250, 80, 100]   # moving-bus: 연분홍
    258 : [180, 30, 80]    # moving-truck: 자홍색
    259 : [255, 0, 0]      # moving-other-vehicle: 빨간색

# mapping 옵션 사용 시, 색상 매핑 설정
mapping_color_map:
    0 : [255, 255, 255]     # unlabeled
    1 : [0, 0, 255]         # road
    2 : [255, 0, 255]       # sidewalk
    3 : [255, 0, 0]         # car
    4 : [0, 0, 0]           # other-vehicle


learning_map:
    0: 0    # unlabeled                   -> 0: unlabeled
    1: 0    # outlier                     -> 0: unlabeled
    10: 3   # car                         -> 3: car
    11: 4   # bicycle                     -> 4: other-vehicle
    13: 3   # bus                         -> 3: car
    15: 4   # motorcycle                  -> 4: other-vehicle
    16: 4   # on-rails                    -> 4: other-vehicle
    18: 3   # truck                       -> 3: car
    20: 4   # other-vehicle               -> 4: other-vehicle
    30: 4   # person                      -> 4: other-vehicle
    31: 4   # bicyclist                   -> 4: other-vehicle
    32: 4   # motorcyclist                -> 4: other-vehicle
    40: 1   # road                        -> 1: road
    44: 1   # parking                     -> 1: road
    48: 2   # sidewalk                    -> 2: sidewalk
    49: 0   # other-ground                -> 0: unlabeled
    50: 0   # building                    -> 0: unlabeled
    51: 0   # fence                       -> 0: unlabeled
    52: 0   # other-structure             -> 0: unlabeled
    60: 1   # lane-marking                -> 1: road
    70: 0   # vegetation                  -> 0: unlabeled
    71: 0   # trunk                       -> 0: unlabeled
    72: 0   # terrain                     -> 0: unlabeled
    80: 0   # pole                        -> 0: unlabeled
    81: 0   # traffic-sign                -> 0: unlabeled
    99: 0   # other-object                -> 0: unlabeled
    252: 3  # moving-car                  -> 3: car
    253: 4  # moving-bicyclist            -> 4: other-vehicle
    254: 4  # moving-person               -> 4: other-vehicle
    255: 4  # moving-motorcyclist         -> 4: other-vehicle
    256: 4  # moving-on-rails             -> 4: other-vehicle
    257: 4  # moving-bus                  -> 4: other-vehicle
    258: 3  # moving-truck                -> 3: car
    259: 4  # moving-other-vehicle        -> 4: other-vehicle


learning_map_inv:
    0: 10  # car -> car
    1: 20  # other-vehicle -> other-vehicle
    2: 40  # road -> road 
    3: 48  # sidewalk -> sidewalk
    4: 0   # unlabeled -> unlabeled