# LiDAR 정보
lidar:
    "manufacturer": "velodyne"
    "H": 64
    "W": 1024
    "fov_up": 3.0
    "fov_down": -25.0


# 라벨 정보 (사용 X)
labels:
    0  : "car"
    1  : "bicycle"
    2  : "motorcycle"
    3  : "truck"
    4  : "bus"
    5  : "person"
    6  : "bicyclist"
    7  : "motorcyclist"
    8  : "road"
    9  : "parking"
    10 : "sidewalk"
    11 : "other-ground"
    12 : "building"
    13 : "fence"
    14 : "vegetation"
    15 : "trunck"
    16 : "terrian"
    17 : "pole"
    18 : "traffic-sign"
    19 : "unlabled"


# 라벨별 BGR 색상 매핑 설정
color_map:
    0   : [255,   0,   0]  # car         - 파란색
    1   : [  0, 255,   0]  # bicycle     - 초록색
    2   : [255, 255,   0]  # motorcycle  - 시안(노랑+파랑)
    3   : [255,   0, 255]  # truck       - 마젠타
    4   : [  0, 165, 255]  # bus         - 오렌지
    5   : [128,   0, 128]  # person      - 보라색
    6   : [144, 238, 144]  # bicyclist   - 연한 초록
    7   : [255, 216, 175]  # motorcyclist - 연한 살구색
    8   : [  0,   0, 255]  # road        - 빨간색
    9   : [128, 128,   0]  # parking     - 청록 계열
    10  : [  0, 255, 255]  # sidewalk    - 노란색
    11  : [ 42,  42, 165]  # other-ground - 진한 갈색
    12  : [128, 128, 128]  # building    - 회색
    13  : [ 64,  64,  64]  # fence       - 어두운 회색
    14  : [ 34, 139,  34]  # vegetation  - 녹색(숲)
    15  : [ 42,  42, 165]  # trunck      - 진한 갈색
    16  : [140, 180, 210]  # terrian     - 베이지 톤
    17  : [  0,   0,   0]  # pole        - 검은색
    18  : [203, 192, 255]  # traffic-sign - 연한 분홍
    19  : [255, 255, 255]  # unlabled    - 흰색



label_map:
    0  : 0
    1  : 1
    2  : 1
    3  : 0
    4  : 0
    5  : 1
    6  : 1
    7  : 1
    8  : 2
    9  : 2
    10 : 3
    11 : 4
    12 : 4
    13 : 4
    14 : 4
    15 : 4
    16 : 4
    17 : 4
    18 : 4
    19 : 4